GET {{host}}/carts/dbc90bd8-e838-4023-9f72-edf05cc6f23e
Accept: application/json

###
POST {{host}}/carts/dbc90bd8-e838-4023-9f72-edf05cc6f23e
Content-Type: application/json

{
  "productId": 2
}

###
POST {{host}}/carts
Content-Type: application/json

{}

###
DELETE {{host}}/products/6
Accept: application/json

###
PUT {{host}}/products/10
Content-Type: application/json

{
  "name": "Update Product name",
  "price": 99.99,
  "categoryId": 2,
  "description": "New updated description"
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "New Product",
  "categoryId": 1,
  "description": "This product is created from the IDE request client app.",
  "price": 499.99
}

###
PUT {{host}}/users/1/change-password
Content-Type: application/json

{
  "oldPassword": "Password@1!",
  "newPassword": "NewPassword"
}

###
DELETE {{host}}/users/6
Accept: application/json

###
PUT {{host}}/users/6
Content-Type: application/json

{
  "name": "Mwibutsa Floribert Updated",
  "email": "updated.fmwibutsa@gmail.com"
}

###
POST {{host}}/users
Content-Type: application/json

{
  "name": "Mwibutsa Floribert",
  "email": "fmwibutsa@gmail.com",
  "password": "PassWord!2"
}

###
###
GET {{host}}/products/15
Accept: application/json

###
GET {{host}}/products
Accept: application/json
x-auth-token: 1234

###
GET {{host}}/users/6
Accept: application/json

###
GET {{host}}/users?sort=name
Accept: application/json

###
