POST {{host}}/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1MTczMDU2LCJleHAiOjE3ODUxODAyNTZ9._T-dFWeIfN9c_dRWt0pyDde2XKybjk8kcOMWcZY2tFr16cMnfruG3rA-h8RVCbpxnqIizaSC2wkiF0uipdpoDQ

{
  "cardId": "1afb331d-03e4-4380-ba63-c537c2d3819a"
}

###
GET {{host}}/admin/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJmbG9yaWJlcnQubXdpYnV0c2FAZ21haWwuY29tIiwibmFtZSI6IldpdGggSGFzaGVkIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODUwNzg2MTUsImV4cCI6MTc4NTA3OTUxNX0.gl8nCkgGiEtdC-t5NExoLts_fGW-jYUZDAwhNelKfqctYR8gY75WKCOtpKdSIPHOUvwrA1WRWSfKgrGhCugumw

###
GET {{host}}/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1MTczMDU2LCJleHAiOjE3ODUxODAyNTZ9._T-dFWeIfN9c_dRWt0pyDde2XKybjk8kcOMWcZY2tFr16cMnfruG3rA-h8RVCbpxnqIizaSC2wkiF0uipdpoDQ

###
POST {{host}}/auth/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmbG9yaWJlcnQubXdpYnV0c2FAZ21haWwuY29tIiwiaWF0IjoxNzg1MDUyMTgyLCJleHAiOjE3ODUxMzg1ODJ9.my8OM84pTT4_ZgLdbYRVnXF-9R-wUHkcs9gv5xWJBKY65fabovxNH3UkSLP1oTBO42qmpGPrC7YTETXQcSrC4Q

{}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Password@1"
}

###
DELETE {{host}}/carts/dbc90bd8-e838-4023-9f72-edf05cc6f23e/items
Content-Type: application/json

###
DELETE {{host}}/carts/dbc90bd8-e838-4023-9f72-edf05cc6f23e/items/1
Content-Type: application/json

###
PUT {{host}}/carts/dbc90bd8-e838-4023-9f72-edf05cc6f23e/items/2
Content-Type: application/json

{
  "quantity": 20
}

###
GET {{host}}/carts/1afb331d-03e4-4380-ba63-c537c2d3819a
Accept: application/json

###
POST {{host}}/carts/1afb331d-03e4-4380-ba63-c537c2d3819a/items
Content-Type: application/json

{
  "productId": 72
}

###
POST {{host}}/carts
Content-Type: application/json

{}

###
DELETE {{host}}/products/6
Accept: application/json

###
PUT {{host}}/products/10
Content-Type: application/json

{
  "name": "Update Product name",
  "price": 99.99,
  "categoryId": 2,
  "description": "New updated description"
}

###
POST {{host}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYW1lIjoiQWRtaW4gVXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1MTcyNjkyLCJleHAiOjE3ODUxNzk4OTJ9.rJITQa6gozdi4i0wXk1bo9vqQ8RfLzd3voHp5b0pYv0TGBa51GG3q2-x42qViusuvXsYTNt4Z2nWAfFd3n7bCQ

{
  "name": "New Product",
  "categoryId": 1,
  "description": "This product is created from the IDE request client app.",
  "price": 499.99
}

###
PUT {{host}}/users/1/change-password
Content-Type: application/json

{
  "oldPassword": "Password@1!",
  "newPassword": "NewPassword"
}

###
DELETE {{host}}/users/6
Accept: application/json

###
PUT {{host}}/users/6
Content-Type: application/json

{
  "name": "Mwibutsa Floribert Updated",
  "email": "updated.fmwibutsa@gmail.com"
}

###
POST {{host}}/users
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin@gmail.com",
  "password": "Password@1"
}

###
###
GET {{host}}/products/15
Accept: application/json

###
GET {{host}}/products
Accept: application/json
x-auth-token: 1234

###
GET {{host}}/users/6
Accept: application/json

###
GET {{host}}/users?sort=name
Accept: application/json

###
